name: wal-g
base: core20
summary: WAL archival and restoration tool for PostgreSQL
description: >
  WAL-G is an archival restoration tool for Postgres (beta for MySQL, MariaDB, MongoDB, and Redis).
  It is the successor of WAL-E with a number of key differences. WAL-G uses LZ4, LZMA, or Brotli
  compression, multiple processors, and non-exclusive base backups for PostgreSQL.
grade: stable
confinement: classic
adopt-info: wal-g
apps:
  wal-g:
    command: bin/wal-g.pg
  pg:
    command: bin/wal-g.pg
  mysql:
    command: bin/wal-g.mysql
  mongo:
    command: bin/wal-g.mongo
  envdir:
    command: usr/bin/envdir
parts:
  wal-g:
    plugin: make
    source: .
    # source: https://github.com/wal-g/wal-g.git
    # source-type: git
    # source-tag: v0.2.16
    build-environment:
      - USE_LIBSODIUM: "1"
      - USE_LZO: "1"
      - CGO_LDFLAGS: "-no-pie"
    override-pull: |
      snapcraftctl pull
      GIT_VER=$(git describe --dirty --always --tags | sed -r 's/v(.*)/\1/g')
      snapcraftctl set-version $GIT_VER
      make install go_deps link_external_deps # link_libsodium both pulls source using curl and builds
    override-build: |
      make unittest
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      make GOBIN=$SNAPCRAFT_PART_INSTALL/bin pg_install
      mv $SNAPCRAFT_PART_INSTALL/bin/wal-g $SNAPCRAFT_PART_INSTALL/bin/wal-g.pg
      make GOBIN=$SNAPCRAFT_PART_INSTALL/bin mysql_install
      mv $SNAPCRAFT_PART_INSTALL/bin/wal-g $SNAPCRAFT_PART_INSTALL/bin/wal-g.mysql
      make GOBIN=$SNAPCRAFT_PART_INSTALL/bin mongo_install
      mv $SNAPCRAFT_PART_INSTALL/bin/wal-g $SNAPCRAFT_PART_INSTALL/bin/wal-g.mongo
    stage:
      - bin/wal-g.pg
      - bin/wal-g.mysql
      - bin/wal-g.mongo
    build-packages:
      - liblzo2-dev
      - cmake
      - build-essential
      - curl
      - git
    build-snaps:
      - go/1.15/stable
  envdir:
    plugin: nil
    stage-packages:
      - daemontools
    stage:
      - usr/bin/envdir
